// Generated by gencpp from file vehicle_control/motorsMsg.msg
// DO NOT EDIT!


#ifndef VEHICLE_CONTROL_MESSAGE_MOTORSMSG_H
#define VEHICLE_CONTROL_MESSAGE_MOTORSMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vehicle_control
{
template <class ContainerAllocator>
struct motorsMsg_
{
  typedef motorsMsg_<ContainerAllocator> Type;

  motorsMsg_()
    : omega1(0)
    , omega2(0)
    , omega3(0)
    , omega4(0)  {
    }
  motorsMsg_(const ContainerAllocator& _alloc)
    : omega1(0)
    , omega2(0)
    , omega3(0)
    , omega4(0)  {
  (void)_alloc;
    }



   typedef int32_t _omega1_type;
  _omega1_type omega1;

   typedef int32_t _omega2_type;
  _omega2_type omega2;

   typedef int32_t _omega3_type;
  _omega3_type omega3;

   typedef int32_t _omega4_type;
  _omega4_type omega4;





  typedef boost::shared_ptr< ::vehicle_control::motorsMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_control::motorsMsg_<ContainerAllocator> const> ConstPtr;

}; // struct motorsMsg_

typedef ::vehicle_control::motorsMsg_<std::allocator<void> > motorsMsg;

typedef boost::shared_ptr< ::vehicle_control::motorsMsg > motorsMsgPtr;
typedef boost::shared_ptr< ::vehicle_control::motorsMsg const> motorsMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_control::motorsMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_control::motorsMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vehicle_control::motorsMsg_<ContainerAllocator1> & lhs, const ::vehicle_control::motorsMsg_<ContainerAllocator2> & rhs)
{
  return lhs.omega1 == rhs.omega1 &&
    lhs.omega2 == rhs.omega2 &&
    lhs.omega3 == rhs.omega3 &&
    lhs.omega4 == rhs.omega4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vehicle_control::motorsMsg_<ContainerAllocator1> & lhs, const ::vehicle_control::motorsMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vehicle_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_control::motorsMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_control::motorsMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_control::motorsMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_control::motorsMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_control::motorsMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_control::motorsMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_control::motorsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6310bddbb1f6c6ea47b30f0419b43b5a";
  }

  static const char* value(const ::vehicle_control::motorsMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6310bddbb1f6c6eaULL;
  static const uint64_t static_value2 = 0x47b30f0419b43b5aULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_control::motorsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_control/motorsMsg";
  }

  static const char* value(const ::vehicle_control::motorsMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_control::motorsMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 omega1\n"
"int32 omega2\n"
"int32 omega3\n"
"int32 omega4\n"
;
  }

  static const char* value(const ::vehicle_control::motorsMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_control::motorsMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.omega1);
      stream.next(m.omega2);
      stream.next(m.omega3);
      stream.next(m.omega4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motorsMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_control::motorsMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_control::motorsMsg_<ContainerAllocator>& v)
  {
    s << indent << "omega1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.omega1);
    s << indent << "omega2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.omega2);
    s << indent << "omega3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.omega3);
    s << indent << "omega4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.omega4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_CONTROL_MESSAGE_MOTORSMSG_H
