# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: mani1
  joint_model_group_pose: home1
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - mani1_joint1
    - mani1_joint2
    - mani1_joint3
    - mani1_joint4
    - mani1_joint5
    - mani1_joint6
    - mani1_joint7
    - mani2_joint1
    - mani2_joint2
    - mani2_joint3
    - mani2_joint4
    - mani2_joint5
    - mani2_joint6
    - mani2_joint7
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: mani1_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - mani1_joint1
      - mani1_joint2
      - mani1_joint3
      - mani1_joint4
      - mani1_joint5
      - mani1_joint6
      - mani1_joint7
  - name: mani2_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - mani2_joint1
      - mani2_joint2
      - mani2_joint3
      - mani2_joint4
      - mani2_joint5
      - mani2_joint6
      - mani2_joint7