// Generated by gencpp from file mobile_control/motorMsg.msg
// DO NOT EDIT!


#ifndef MOBILE_CONTROL_MESSAGE_MOTORMSG_H
#define MOBILE_CONTROL_MESSAGE_MOTORMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mobile_control
{
template <class ContainerAllocator>
struct motorMsg_
{
  typedef motorMsg_<ContainerAllocator> Type;

  motorMsg_()
    : header()
    , omega1(0)
    , omega2(0)
    , omega3(0)
    , omega4(0)  {
    }
  motorMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , omega1(0)
    , omega2(0)
    , omega3(0)
    , omega4(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _omega1_type;
  _omega1_type omega1;

   typedef int32_t _omega2_type;
  _omega2_type omega2;

   typedef int32_t _omega3_type;
  _omega3_type omega3;

   typedef int32_t _omega4_type;
  _omega4_type omega4;





  typedef boost::shared_ptr< ::mobile_control::motorMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobile_control::motorMsg_<ContainerAllocator> const> ConstPtr;

}; // struct motorMsg_

typedef ::mobile_control::motorMsg_<std::allocator<void> > motorMsg;

typedef boost::shared_ptr< ::mobile_control::motorMsg > motorMsgPtr;
typedef boost::shared_ptr< ::mobile_control::motorMsg const> motorMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobile_control::motorMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobile_control::motorMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobile_control::motorMsg_<ContainerAllocator1> & lhs, const ::mobile_control::motorMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.omega1 == rhs.omega1 &&
    lhs.omega2 == rhs.omega2 &&
    lhs.omega3 == rhs.omega3 &&
    lhs.omega4 == rhs.omega4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobile_control::motorMsg_<ContainerAllocator1> & lhs, const ::mobile_control::motorMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobile_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mobile_control::motorMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobile_control::motorMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_control::motorMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobile_control::motorMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_control::motorMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobile_control::motorMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobile_control::motorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc96ee74795dd87ba70013bf55e8a168";
  }

  static const char* value(const ::mobile_control::motorMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc96ee74795dd87bULL;
  static const uint64_t static_value2 = 0xa70013bf55e8a168ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobile_control::motorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobile_control/motorMsg";
  }

  static const char* value(const ::mobile_control::motorMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobile_control::motorMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int32 omega1\n"
"int32 omega2\n"
"int32 omega3\n"
"int32 omega4\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mobile_control::motorMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobile_control::motorMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.omega1);
      stream.next(m.omega2);
      stream.next(m.omega3);
      stream.next(m.omega4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motorMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobile_control::motorMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobile_control::motorMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "omega1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.omega1);
    s << indent << "omega2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.omega2);
    s << indent << "omega3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.omega3);
    s << indent << "omega4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.omega4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILE_CONTROL_MESSAGE_MOTORMSG_H
