// Generated by gencpp from file msgpkg/fabric.msg
// DO NOT EDIT!


#ifndef MSGPKG_MESSAGE_FABRIC_H
#define MSGPKG_MESSAGE_FABRIC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msgpkg
{
template <class ContainerAllocator>
struct fabric_
{
  typedef fabric_<ContainerAllocator> Type;

  fabric_()
    : Data1(0)
    , Data2(0)  {
    }
  fabric_(const ContainerAllocator& _alloc)
    : Data1(0)
    , Data2(0)  {
  (void)_alloc;
    }



   typedef int32_t _Data1_type;
  _Data1_type Data1;

   typedef int32_t _Data2_type;
  _Data2_type Data2;





  typedef boost::shared_ptr< ::msgpkg::fabric_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgpkg::fabric_<ContainerAllocator> const> ConstPtr;

}; // struct fabric_

typedef ::msgpkg::fabric_<std::allocator<void> > fabric;

typedef boost::shared_ptr< ::msgpkg::fabric > fabricPtr;
typedef boost::shared_ptr< ::msgpkg::fabric const> fabricConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgpkg::fabric_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgpkg::fabric_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgpkg::fabric_<ContainerAllocator1> & lhs, const ::msgpkg::fabric_<ContainerAllocator2> & rhs)
{
  return lhs.Data1 == rhs.Data1 &&
    lhs.Data2 == rhs.Data2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgpkg::fabric_<ContainerAllocator1> & lhs, const ::msgpkg::fabric_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgpkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msgpkg::fabric_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgpkg::fabric_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgpkg::fabric_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgpkg::fabric_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgpkg::fabric_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgpkg::fabric_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgpkg::fabric_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b586c67171812310749927e0856b34be";
  }

  static const char* value(const ::msgpkg::fabric_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb586c67171812310ULL;
  static const uint64_t static_value2 = 0x749927e0856b34beULL;
};

template<class ContainerAllocator>
struct DataType< ::msgpkg::fabric_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgpkg/fabric";
  }

  static const char* value(const ::msgpkg::fabric_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgpkg::fabric_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 Data1\n"
"int32 Data2\n"
"\n"
;
  }

  static const char* value(const ::msgpkg::fabric_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgpkg::fabric_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Data1);
      stream.next(m.Data2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fabric_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgpkg::fabric_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgpkg::fabric_<ContainerAllocator>& v)
  {
    s << indent << "Data1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Data1);
    s << indent << "Data2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Data2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGPKG_MESSAGE_FABRIC_H
