// Generated by gencpp from file msgpkg/msgf2.msg
// DO NOT EDIT!


#ifndef MSGPKG_MESSAGE_MSGF2_H
#define MSGPKG_MESSAGE_MSGF2_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msgpkg
{
template <class ContainerAllocator>
struct msgf2_
{
  typedef msgf2_<ContainerAllocator> Type;

  msgf2_()
    : for2(0.0)  {
    }
  msgf2_(const ContainerAllocator& _alloc)
    : for2(0.0)  {
  (void)_alloc;
    }



   typedef float _for2_type;
  _for2_type for2;





  typedef boost::shared_ptr< ::msgpkg::msgf2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgpkg::msgf2_<ContainerAllocator> const> ConstPtr;

}; // struct msgf2_

typedef ::msgpkg::msgf2_<std::allocator<void> > msgf2;

typedef boost::shared_ptr< ::msgpkg::msgf2 > msgf2Ptr;
typedef boost::shared_ptr< ::msgpkg::msgf2 const> msgf2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgpkg::msgf2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgpkg::msgf2_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgpkg::msgf2_<ContainerAllocator1> & lhs, const ::msgpkg::msgf2_<ContainerAllocator2> & rhs)
{
  return lhs.for2 == rhs.for2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgpkg::msgf2_<ContainerAllocator1> & lhs, const ::msgpkg::msgf2_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgpkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msgpkg::msgf2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgpkg::msgf2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgpkg::msgf2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgpkg::msgf2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgpkg::msgf2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgpkg::msgf2_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgpkg::msgf2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "055ebaaa36f43d418526ea4a0cc9f35e";
  }

  static const char* value(const ::msgpkg::msgf2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x055ebaaa36f43d41ULL;
  static const uint64_t static_value2 = 0x8526ea4a0cc9f35eULL;
};

template<class ContainerAllocator>
struct DataType< ::msgpkg::msgf2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgpkg/msgf2";
  }

  static const char* value(const ::msgpkg::msgf2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgpkg::msgf2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 for2\n"
"\n"
;
  }

  static const char* value(const ::msgpkg::msgf2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgpkg::msgf2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.for2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgf2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgpkg::msgf2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgpkg::msgf2_<ContainerAllocator>& v)
  {
    s << indent << "for2: ";
    Printer<float>::stream(s, indent + "  ", v.for2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGPKG_MESSAGE_MSGF2_H
