// Generated by gencpp from file msgpkg/msgf1.msg
// DO NOT EDIT!


#ifndef MSGPKG_MESSAGE_MSGF1_H
#define MSGPKG_MESSAGE_MSGF1_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msgpkg
{
template <class ContainerAllocator>
struct msgf1_
{
  typedef msgf1_<ContainerAllocator> Type;

  msgf1_()
    : for1(0.0)  {
    }
  msgf1_(const ContainerAllocator& _alloc)
    : for1(0.0)  {
  (void)_alloc;
    }



   typedef float _for1_type;
  _for1_type for1;





  typedef boost::shared_ptr< ::msgpkg::msgf1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgpkg::msgf1_<ContainerAllocator> const> ConstPtr;

}; // struct msgf1_

typedef ::msgpkg::msgf1_<std::allocator<void> > msgf1;

typedef boost::shared_ptr< ::msgpkg::msgf1 > msgf1Ptr;
typedef boost::shared_ptr< ::msgpkg::msgf1 const> msgf1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgpkg::msgf1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgpkg::msgf1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgpkg::msgf1_<ContainerAllocator1> & lhs, const ::msgpkg::msgf1_<ContainerAllocator2> & rhs)
{
  return lhs.for1 == rhs.for1;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgpkg::msgf1_<ContainerAllocator1> & lhs, const ::msgpkg::msgf1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgpkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msgpkg::msgf1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgpkg::msgf1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgpkg::msgf1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgpkg::msgf1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgpkg::msgf1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgpkg::msgf1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgpkg::msgf1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e496f6ad40f2ceb95bb6fa115defb5e7";
  }

  static const char* value(const ::msgpkg::msgf1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe496f6ad40f2ceb9ULL;
  static const uint64_t static_value2 = 0x5bb6fa115defb5e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgpkg::msgf1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgpkg/msgf1";
  }

  static const char* value(const ::msgpkg::msgf1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgpkg::msgf1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 for1\n"
"\n"
;
  }

  static const char* value(const ::msgpkg::msgf1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgpkg::msgf1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.for1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgf1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgpkg::msgf1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgpkg::msgf1_<ContainerAllocator>& v)
  {
    s << indent << "for1: ";
    Printer<float>::stream(s, indent + "  ", v.for1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGPKG_MESSAGE_MSGF1_H
