// Generated by gencpp from file msgpkg/msgmag.msg
// DO NOT EDIT!


#ifndef MSGPKG_MESSAGE_MSGMAG_H
#define MSGPKG_MESSAGE_MSGMAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msgpkg
{
template <class ContainerAllocator>
struct msgmag_
{
  typedef msgmag_<ContainerAllocator> Type;

  msgmag_()
    : mag(0.0)  {
    }
  msgmag_(const ContainerAllocator& _alloc)
    : mag(0.0)  {
  (void)_alloc;
    }



   typedef float _mag_type;
  _mag_type mag;





  typedef boost::shared_ptr< ::msgpkg::msgmag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgpkg::msgmag_<ContainerAllocator> const> ConstPtr;

}; // struct msgmag_

typedef ::msgpkg::msgmag_<std::allocator<void> > msgmag;

typedef boost::shared_ptr< ::msgpkg::msgmag > msgmagPtr;
typedef boost::shared_ptr< ::msgpkg::msgmag const> msgmagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgpkg::msgmag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgpkg::msgmag_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgpkg::msgmag_<ContainerAllocator1> & lhs, const ::msgpkg::msgmag_<ContainerAllocator2> & rhs)
{
  return lhs.mag == rhs.mag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgpkg::msgmag_<ContainerAllocator1> & lhs, const ::msgpkg::msgmag_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgpkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msgpkg::msgmag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgpkg::msgmag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgpkg::msgmag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgpkg::msgmag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgpkg::msgmag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgpkg::msgmag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgpkg::msgmag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "938244a09b40aebc4fca0d898d8e25f1";
  }

  static const char* value(const ::msgpkg::msgmag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x938244a09b40aebcULL;
  static const uint64_t static_value2 = 0x4fca0d898d8e25f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgpkg::msgmag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgpkg/msgmag";
  }

  static const char* value(const ::msgpkg::msgmag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgpkg::msgmag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 mag\n"
;
  }

  static const char* value(const ::msgpkg::msgmag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgpkg::msgmag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgmag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgpkg::msgmag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgpkg::msgmag_<ContainerAllocator>& v)
  {
    s << indent << "mag: ";
    Printer<float>::stream(s, indent + "  ", v.mag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGPKG_MESSAGE_MSGMAG_H
