// Generated by gencpp from file msgpkg/msgtor.msg
// DO NOT EDIT!


#ifndef MSGPKG_MESSAGE_MSGTOR_H
#define MSGPKG_MESSAGE_MSGTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msgpkg
{
template <class ContainerAllocator>
struct msgtor_
{
  typedef msgtor_<ContainerAllocator> Type;

  msgtor_()
    : tor(0.0)  {
    }
  msgtor_(const ContainerAllocator& _alloc)
    : tor(0.0)  {
  (void)_alloc;
    }



   typedef float _tor_type;
  _tor_type tor;





  typedef boost::shared_ptr< ::msgpkg::msgtor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgpkg::msgtor_<ContainerAllocator> const> ConstPtr;

}; // struct msgtor_

typedef ::msgpkg::msgtor_<std::allocator<void> > msgtor;

typedef boost::shared_ptr< ::msgpkg::msgtor > msgtorPtr;
typedef boost::shared_ptr< ::msgpkg::msgtor const> msgtorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgpkg::msgtor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgpkg::msgtor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgpkg::msgtor_<ContainerAllocator1> & lhs, const ::msgpkg::msgtor_<ContainerAllocator2> & rhs)
{
  return lhs.tor == rhs.tor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgpkg::msgtor_<ContainerAllocator1> & lhs, const ::msgpkg::msgtor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgpkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msgpkg::msgtor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgpkg::msgtor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgpkg::msgtor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgpkg::msgtor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgpkg::msgtor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgpkg::msgtor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgpkg::msgtor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "087bb50d3e0b88ee3559c736b6ddf16b";
  }

  static const char* value(const ::msgpkg::msgtor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x087bb50d3e0b88eeULL;
  static const uint64_t static_value2 = 0x3559c736b6ddf16bULL;
};

template<class ContainerAllocator>
struct DataType< ::msgpkg::msgtor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgpkg/msgtor";
  }

  static const char* value(const ::msgpkg::msgtor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgpkg::msgtor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 tor\n"
;
  }

  static const char* value(const ::msgpkg::msgtor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgpkg::msgtor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgtor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgpkg::msgtor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgpkg::msgtor_<ContainerAllocator>& v)
  {
    s << indent << "tor: ";
    Printer<float>::stream(s, indent + "  ", v.tor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGPKG_MESSAGE_MSGTOR_H
