// Generated by gencpp from file msgpkg/multi_sensor.msg
// DO NOT EDIT!


#ifndef MSGPKG_MESSAGE_MULTI_SENSOR_H
#define MSGPKG_MESSAGE_MULTI_SENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msgpkg
{
template <class ContainerAllocator>
struct multi_sensor_
{
  typedef multi_sensor_<ContainerAllocator> Type;

  multi_sensor_()
    : Data1(0)
    , Data2(0)
    , Data3(0)  {
    }
  multi_sensor_(const ContainerAllocator& _alloc)
    : Data1(0)
    , Data2(0)
    , Data3(0)  {
  (void)_alloc;
    }



   typedef int32_t _Data1_type;
  _Data1_type Data1;

   typedef int32_t _Data2_type;
  _Data2_type Data2;

   typedef int32_t _Data3_type;
  _Data3_type Data3;





  typedef boost::shared_ptr< ::msgpkg::multi_sensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgpkg::multi_sensor_<ContainerAllocator> const> ConstPtr;

}; // struct multi_sensor_

typedef ::msgpkg::multi_sensor_<std::allocator<void> > multi_sensor;

typedef boost::shared_ptr< ::msgpkg::multi_sensor > multi_sensorPtr;
typedef boost::shared_ptr< ::msgpkg::multi_sensor const> multi_sensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgpkg::multi_sensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgpkg::multi_sensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgpkg::multi_sensor_<ContainerAllocator1> & lhs, const ::msgpkg::multi_sensor_<ContainerAllocator2> & rhs)
{
  return lhs.Data1 == rhs.Data1 &&
    lhs.Data2 == rhs.Data2 &&
    lhs.Data3 == rhs.Data3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgpkg::multi_sensor_<ContainerAllocator1> & lhs, const ::msgpkg::multi_sensor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgpkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msgpkg::multi_sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgpkg::multi_sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgpkg::multi_sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgpkg::multi_sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgpkg::multi_sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgpkg::multi_sensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgpkg::multi_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6db23ffcc32ab1d35461ec471b4d6a77";
  }

  static const char* value(const ::msgpkg::multi_sensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6db23ffcc32ab1d3ULL;
  static const uint64_t static_value2 = 0x5461ec471b4d6a77ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgpkg::multi_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgpkg/multi_sensor";
  }

  static const char* value(const ::msgpkg::multi_sensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgpkg::multi_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 Data1\n"
"int32 Data2\n"
"int32 Data3\n"
;
  }

  static const char* value(const ::msgpkg::multi_sensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgpkg::multi_sensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Data1);
      stream.next(m.Data2);
      stream.next(m.Data3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct multi_sensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgpkg::multi_sensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgpkg::multi_sensor_<ContainerAllocator>& v)
  {
    s << indent << "Data1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Data1);
    s << indent << "Data2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Data2);
    s << indent << "Data3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Data3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGPKG_MESSAGE_MULTI_SENSOR_H
