// Generated by gencpp from file msgpkg/Val.msg
// DO NOT EDIT!


#ifndef MSGPKG_MESSAGE_VAL_H
#define MSGPKG_MESSAGE_VAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msgpkg
{
template <class ContainerAllocator>
struct Val_
{
  typedef Val_<ContainerAllocator> Type;

  Val_()
    : position(0.0)  {
    }
  Val_(const ContainerAllocator& _alloc)
    : position(0.0)  {
  (void)_alloc;
    }



   typedef float _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::msgpkg::Val_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msgpkg::Val_<ContainerAllocator> const> ConstPtr;

}; // struct Val_

typedef ::msgpkg::Val_<std::allocator<void> > Val;

typedef boost::shared_ptr< ::msgpkg::Val > ValPtr;
typedef boost::shared_ptr< ::msgpkg::Val const> ValConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msgpkg::Val_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msgpkg::Val_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msgpkg::Val_<ContainerAllocator1> & lhs, const ::msgpkg::Val_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msgpkg::Val_<ContainerAllocator1> & lhs, const ::msgpkg::Val_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msgpkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::msgpkg::Val_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msgpkg::Val_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgpkg::Val_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msgpkg::Val_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgpkg::Val_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msgpkg::Val_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msgpkg::Val_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4e11b3af29ed247b2bd150d3f4540f9";
  }

  static const char* value(const ::msgpkg::Val_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4e11b3af29ed247ULL;
  static const uint64_t static_value2 = 0xb2bd150d3f4540f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::msgpkg::Val_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msgpkg/Val";
  }

  static const char* value(const ::msgpkg::Val_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msgpkg::Val_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 position\n"
;
  }

  static const char* value(const ::msgpkg::Val_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msgpkg::Val_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Val_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msgpkg::Val_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msgpkg::Val_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSGPKG_MESSAGE_VAL_H
