# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from msgpkg/realVal3.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class realVal3(genpy.Message):
  _md5sum = "8a1e673a40df61e466a877827a9e4183"
  _type = "msgpkg/realVal3"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 realPos1
int64 realPos2
int64 adc1
int64 adc2
int64 adc3
int64 adc4
float64 command1
float64 command2
"""
  __slots__ = ['realPos1','realPos2','adc1','adc2','adc3','adc4','command1','command2']
  _slot_types = ['int64','int64','int64','int64','int64','int64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       realPos1,realPos2,adc1,adc2,adc3,adc4,command1,command2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(realVal3, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.realPos1 is None:
        self.realPos1 = 0
      if self.realPos2 is None:
        self.realPos2 = 0
      if self.adc1 is None:
        self.adc1 = 0
      if self.adc2 is None:
        self.adc2 = 0
      if self.adc3 is None:
        self.adc3 = 0
      if self.adc4 is None:
        self.adc4 = 0
      if self.command1 is None:
        self.command1 = 0.
      if self.command2 is None:
        self.command2 = 0.
    else:
      self.realPos1 = 0
      self.realPos2 = 0
      self.adc1 = 0
      self.adc2 = 0
      self.adc3 = 0
      self.adc4 = 0
      self.command1 = 0.
      self.command2 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6q2d().pack(_x.realPos1, _x.realPos2, _x.adc1, _x.adc2, _x.adc3, _x.adc4, _x.command1, _x.command2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.realPos1, _x.realPos2, _x.adc1, _x.adc2, _x.adc3, _x.adc4, _x.command1, _x.command2,) = _get_struct_6q2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6q2d().pack(_x.realPos1, _x.realPos2, _x.adc1, _x.adc2, _x.adc3, _x.adc4, _x.command1, _x.command2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 64
      (_x.realPos1, _x.realPos2, _x.adc1, _x.adc2, _x.adc3, _x.adc4, _x.command1, _x.command2,) = _get_struct_6q2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6q2d = None
def _get_struct_6q2d():
    global _struct_6q2d
    if _struct_6q2d is None:
        _struct_6q2d = struct.Struct("<6q2d")
    return _struct_6q2d
